# Vendor Stan functions from primarycensored into EpiNow2
#
# Usage: Rscript inst/dev/vendor-primarycensored.R

library(primarycensored)

output_file <- "inst/stan/functions/primarycensored.stan"

# primarycensored_ode, dist_lcdf, primary_lpdf, and
# expgrowth_lpdf are passed by reference (e.g. to ode_rk45)
# so the dependency resolver does not detect them
# automatically. We list them explicitly here.
funcs <- c(
  "primarycensored_lpmf",
  "primarycensored_sone_pmf_vectorized",
  "primarycensored_ode",
  "dist_lcdf",
  "primary_lpdf",
  "expgrowth_lpdf"
)

invisible(pcd_load_stan_functions(
  functions = funcs,
  dependencies = TRUE,
  write_to_file = TRUE,
  output_file = output_file
))

version <- packageVersion("primarycensored")

# Prepend an auto-generated header so the vendored file is clearly
# marked as not-for-hand-editing.
header <- c(
  sprintf(
    "// Stan functions from primarycensored version %s.",
    as.character(version)
  ),
  paste(
    "// AUTO-GENERATED by inst/dev/vendor-primarycensored.R;",
    "do not edit by hand."
  ),
  "// Re-run the vendor script to refresh from the upstream package."
)
body <- readLines(output_file)
# Drop the existing version banner if present so we don't duplicate it.
if (length(body) > 0 && grepl("^// Stan functions from primarycensored", body[1])) {
  body <- body[-1]
}
writeLines(c(header, body), output_file)

all_funcs <- unique(unlist(lapply(
  funcs, pcd_stan_function_deps
)))
cat(
  "Vendored", length(all_funcs), "Stan functions",
  "from primarycensored", as.character(version), "\n"
)
cat("Functions:", paste(all_funcs, collapse = ", "), "\n")
cat("Written to:", output_file, "\n")
