# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
repos:
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.1.3
    hooks: 
    -   id: style-files
        args: [--style_pkg=styler, --style_fun=tidyverse_style]    
    -   id: roxygenize
    # codemeta must be above use-tidy-description when both are used
    # -   id: codemeta-description-updated
    -   id: use-tidy-description
    -   id: spell-check
        args: [--lang=en-GB]
        exclude: >
          (?x)^(
          data/.*| 
          (.*/|)\.Rprofile|
          (.*/|)\.Renviron|
          (.*/|)\.gitignore|
          (.*/|)NAMESPACE|
          (.*/|)WORDLIST|
          (.*/|)\.travis.yml|
          (.*/|)appveyor.yml|
          (.*/|)\.Rbuildignore|
          (.*/|)\.pre-commit-.*|
          .*\.[rR]|
          .*\.Rproj|
          .*\.py|
          .*\.feather|
          .*\.rds|
          .*\.Rds|
          .*\.sh|
          .*\.RData
          )$
    -   id: lintr
    -   id: readme-rmd-rendered
    -   id: parsable-R
    -   id: no-browser-statement
    -   id: deps-in-desc
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks: 
    -   id: check-added-large-files
        args: ['--maxkb=200']
    -   id: end-of-file-fixer
        exclude: '\.Rd'
-   repo: local
    hooks:
    -   id: forbid-to-commit
        name: Don't commit common R artifacts
        entry: Cannot commit .Rhistory, or .RData.
        language: fail
        files: '\.Rhistory|\.RData$'
        # `exclude: <regex>` to allow committing specific files.
