EpiNow2 Stan Functions: /github/workspace/inst/stan/functions/gaussian_process.stan File Reference
gaussian_process.stan File Reference
Functions in this File
vector diagSPD_EQ (real alpha, real rho, real L, int M)
vector diagSPD_Matern12 (real alpha, real rho, real L, int M)
vector diagSPD_Matern32 (real alpha, real rho, real L, int M)
vector diagSPD_Matern52 (real alpha, real rho, real L, int M)
vector diagSPD_Periodic (real alpha, real rho, int M)
void gaussian_process_lp (vector eta)
matrix PHI (int N, int M, real L, vector x)
matrix PHI_periodic (int N, int M, real w0, vector x)
matrix setup_gp (int M, real L, int dimension, int is_periodic, real w0)
int setup_noise (int ot_h, int t, int horizon, int estimate_r, int stationary, int future_fixed, int fixed_from)
vector update_gp (matrix PHI, int M, real L, real alpha, real rho, vector eta, int type, real nu)
Function Documentation
update_gp()
vector update_gp (matrix PHI, int M, real L, real alpha, real rho, vector eta, int type, real nu)
Update Gaussian process using spectral densities
Parameters
PHI Basis functions matrix
M Number of basis functions
L Length of the interval
alpha Scaling parameter
rho Length scale parameter
eta Vector of noise terms
type Type of kernel (0: SE, 1: Periodic, 2: Matern)
nu Smoothness parameter for Matern kernel
Returns
A vector of updated noise terms
Definition at line 196 of file gaussian_process.stan.
{
  vector[type == 1 ? 2 * M : M] diagSPD;    // spectral density
  // GP in noise - spectral densities
  if (type == 0) {
    diagSPD = diagSPD_EQ(alpha, rho, L, M);
  } else if (type == 1) {
    diagSPD = diagSPD_Periodic(alpha, rho, M);
  } else if (type == 2) {
    if (nu == 0.5) {
      diagSPD = diagSPD_Matern12(alpha, rho, L, M);
    } else if (nu == 1.5) {
      diagSPD = diagSPD_Matern32(alpha, rho, L, M);
    } else if (nu == 2.5) {
      diagSPD = diagSPD_Matern52(alpha, rho, L, M);
    } else {
      reject("nu must be one of 1/2, 3/2 or 5/2; found nu=", nu);
    }
  }
  return PHI * (diagSPD .* eta);
}
References diagSPD_EQ(), diagSPD_Matern12(), diagSPD_Matern32(), diagSPD_Matern52(), diagSPD_Periodic(), and PHI().