EpiNow2 Stan Functions: /github/workspace/inst/stan/functions/primarycensored.stan File Reference
primarycensored.stan File Reference
Functions in this File
real expgrowth_lpdf (real x, real xmin, real xmax, real r)
int check_for_analytical (int dist_id, int primary_id)
real primarycensored_gamma_uniform_lcdf (data real d, real q, array[] real params, data real pwindow)
real primarycensored_lognormal_uniform_lcdf (data real d, real q, array[] real params, data real pwindow)
real log_weibull_g (real t, real shape, real scale)
real primarycensored_weibull_uniform_lcdf (data real d, real q, array[] real params, data real pwindow)
real primarycensored_analytical_lcdf_raw (data real d, int dist_id, array[] real params, data real pwindow, int primary_id)
real primarycensored_analytical_lcdf (data real d, int dist_id, array[] real params, data real pwindow, data real L, data real D, int primary_id, array[] real primary_params)
real primarycensored_analytical_cdf (data real d, int dist_id, array[] real params, data real pwindow, data real L, data real D, int primary_id, array[] real primary_params)
int dist_has_positive_support (data int dist_id)
real dist_lcdf (real delay, array[] real params, int dist_id)
real primary_lpdf (real x, int primary_id, array[] real params, real xmin, real xmax)
vector primarycensored_ode (real t, vector y, array[] real theta, array[] real x_r, array[] int x_i)
real primarycensored_log_normalizer (real log_cdf_D, real log_cdf_L, real L)
real primarycensored_apply_truncation (real log_cdf, real log_cdf_L, real log_normalizer, real L)
vector primarycensored_truncation_bounds (data real L, data real D, data int dist_id, array[] real params, data real pwindow, data int primary_id, array[] real primary_params)
real primarycensored_cdf (data real d, data int dist_id, array[] real params, data real pwindow, data real L, data real D, data int primary_id, array[] real primary_params)
real primarycensored_lcdf (data real d, data int dist_id, array[] real params, data real pwindow, data real L, data real D, data int primary_id, array[] real primary_params)
real primarycensored_lpmf (data int d, data int dist_id, array[] real params, data real pwindow, data real d_upper, data real L, data real D, data int primary_id, array[] real primary_params)
vector primarycensored_sone_lpmf_vectorized (data int max_delay, data real L, data real D, data int dist_id, array[] real params, data real pwindow, data int primary_id, array[] real primary_params)
vector primarycensored_sone_pmf_vectorized (data int max_delay, data real L, data real D, data int dist_id, array[] real params, data real pwindow, data int primary_id, array[] real primary_params)
Function Documentation
check_for_analytical()
int check_for_analytical (int dist_id, int primary_id)
Definition at line 12 of file primarycensored.stan.
Referenced by primarycensored_cdf(), and primarycensored_lcdf().
dist_has_positive_support()
int dist_has_positive_support (data int dist_id)
Definition at line 175 of file primarycensored.stan.
Referenced by dist_lcdf(), primarycensored_cdf(), primarycensored_lcdf(), primarycensored_lpmf(), primarycensored_sone_lpmf_vectorized(), and primarycensored_truncation_bounds().
dist_lcdf()
real dist_lcdf (real delay, array[]real params, int dist_id)
Definition at line 188 of file primarycensored.stan.
References dist_has_positive_support().
Referenced by primarycensored_ode().
expgrowth_lpdf()
real expgrowth_lpdf (real x, real xmin, real xmax, real r)
Definition at line 2 of file primarycensored.stan.
Referenced by primary_lpdf().
log_weibull_g()
real log_weibull_g (real t, real shape, real scale)
Definition at line 91 of file primarycensored.stan.
Referenced by primarycensored_weibull_uniform_lcdf().
primary_lpdf()
real primary_lpdf (real x, int primary_id, array[]real params, real xmin, real xmax)
Definition at line 214 of file primarycensored.stan.
References expgrowth_lpdf().
Referenced by primarycensored_ode().
primarycensored_analytical_cdf()
real primarycensored_analytical_cdf (data real d, int dist_id, array[]real params, data real pwindow, data real L, data real D, int primary_id, array[]real primary_params)
Definition at line 168 of file primarycensored.stan.
References primarycensored_analytical_lcdf().
Referenced by primarycensored_cdf().
primarycensored_analytical_lcdf()
real primarycensored_analytical_lcdf (data real d, int dist_id, array[]real params, data real pwindow, data real L, data real D, int primary_id, array[]real primary_params)
Definition at line 142 of file primarycensored.stan.
References primarycensored_analytical_lcdf_raw(), primarycensored_apply_truncation(), primarycensored_log_normalizer(), and primarycensored_truncation_bounds().
Referenced by primarycensored_analytical_cdf(), and primarycensored_lcdf().
primarycensored_analytical_lcdf_raw()
real primarycensored_analytical_lcdf_raw (data real d, int dist_id, array[]real params, data real pwindow, int primary_id)
Definition at line 127 of file primarycensored.stan.
References primarycensored_gamma_uniform_lcdf(), primarycensored_lognormal_uniform_lcdf(), and primarycensored_weibull_uniform_lcdf().
Referenced by primarycensored_analytical_lcdf().
primarycensored_apply_truncation()
real primarycensored_apply_truncation (real log_cdf, real log_cdf_L, real log_normalizer, real L)
Definition at line 253 of file primarycensored.stan.
Referenced by primarycensored_analytical_lcdf(), primarycensored_cdf(), and primarycensored_lcdf().
primarycensored_cdf()
real primarycensored_cdf (data real d, data int dist_id, array[]real params, data real pwindow, data real L, data real D, data int primary_id, array[]real primary_params)
Definition at line 298 of file primarycensored.stan.
References check_for_analytical(), dist_has_positive_support(), primarycensored_analytical_cdf(), primarycensored_apply_truncation(), primarycensored_log_normalizer(), primarycensored_ode(), and primarycensored_truncation_bounds().
Referenced by primarycensored_lcdf().
primarycensored_gamma_uniform_lcdf()
real primarycensored_gamma_uniform_lcdf (data real d, real q, array[]real params, data real pwindow)
Definition at line 18 of file primarycensored.stan.
Referenced by primarycensored_analytical_lcdf_raw().
primarycensored_lcdf()
real primarycensored_lcdf (data real d, data int dist_id, array[]real params, data real pwindow, data real L, data real D, data int primary_id, array[]real primary_params)
Definition at line 354 of file primarycensored.stan.
References check_for_analytical(), dist_has_positive_support(), primarycensored_analytical_lcdf(), primarycensored_apply_truncation(), primarycensored_cdf(), primarycensored_log_normalizer(), and primarycensored_truncation_bounds().
Referenced by primarycensored_lpmf(), primarycensored_sone_lpmf_vectorized(), and primarycensored_truncation_bounds().
primarycensored_log_normalizer()
real primarycensored_log_normalizer (real log_cdf_D, real log_cdf_L, real L)
Definition at line 246 of file primarycensored.stan.
Referenced by primarycensored_analytical_lcdf(), primarycensored_cdf(), primarycensored_lcdf(), primarycensored_lpmf(), and primarycensored_sone_lpmf_vectorized().
primarycensored_lognormal_uniform_lcdf()
real primarycensored_lognormal_uniform_lcdf (data real d, real q, array[]real params, data real pwindow)
Definition at line 58 of file primarycensored.stan.
Referenced by primarycensored_analytical_lcdf_raw().
primarycensored_lpmf()
real primarycensored_lpmf (data int d, data int dist_id, array[]real params, data real pwindow, data real d_upper, data real L, data real D, data int primary_id, array[]real primary_params)
Definition at line 402 of file primarycensored.stan.
References dist_has_positive_support(), primarycensored_lcdf(), and primarycensored_log_normalizer().
primarycensored_ode()
vector primarycensored_ode (real t, vector y, array[]real theta, array[]real x_r, array[]int x_i)
Definition at line 221 of file primarycensored.stan.
References dist_lcdf(), and primary_lpdf().
Referenced by primarycensored_cdf().
primarycensored_sone_lpmf_vectorized()
vector primarycensored_sone_lpmf_vectorized (data int max_delay, data real L, data real D, data int dist_id, array[]real params, data real pwindow, data int primary_id, array[]real primary_params)
Definition at line 470 of file primarycensored.stan.
References dist_has_positive_support(), primarycensored_lcdf(), and primarycensored_log_normalizer().
Referenced by primarycensored_sone_pmf_vectorized().
primarycensored_sone_pmf_vectorized()
vector primarycensored_sone_pmf_vectorized (data int max_delay, data real L, data real D, data int dist_id, array[]real params, data real pwindow, data int primary_id, array[]real primary_params)
Definition at line 565 of file primarycensored.stan.
References primarycensored_sone_lpmf_vectorized().
Referenced by discretised_pmf().
primarycensored_truncation_bounds()
vector primarycensored_truncation_bounds (data real L, data real D, data int dist_id, array[]real params, data real pwindow, data int primary_id, array[]real primary_params)
Definition at line 261 of file primarycensored.stan.
References dist_has_positive_support(), and primarycensored_lcdf().
Referenced by primarycensored_analytical_lcdf(), primarycensored_cdf(), and primarycensored_lcdf().
primarycensored_weibull_uniform_lcdf()
real primarycensored_weibull_uniform_lcdf (data real d, real q, array[]real params, data real pwindow)
Definition at line 96 of file primarycensored.stan.
References log_weibull_g().
Referenced by primarycensored_analytical_lcdf_raw().