#' Get accumulation flags from data
#'
#' @description Returns the `accumulate` column if present, otherwise
#'   a vector of `FALSE` (no accumulation).
#' @param data A data.table that may contain an `accumulate` column.
#' @return A logical vector of length `nrow(data)`.
#' @keywords internal
get_accumulate <- function(data) {
  if ("accumulate" %in% colnames(data)) {
    data$accumulate
  } else {
    rep(FALSE, nrow(data))
  }
}

#' Construct the Required Future Rt assumption
#'
#' @description
#' Converts the `future` argument from [rt_opts()] into arguments that can be
#' passed to stan.
#'
#' @param future A character string or integer. This argument indicates how to
#' set future Rt values. Supported options are to project using the Rt model
#' ("project"), to use the latest estimate based on partial data ("latest"),
#' to use the latest estimate based on data that is over 50% complete
#' ("estimate"). If an integer is supplied then the Rt estimate from this many
#' days into the future (or past if negative) past will be used forwards in
#' time.
#'
#' @param delay Numeric mean delay
#' @importFrom rlang arg_match
#' @keywords internal
#' @return A list containing a logical called fixed and an integer called from
create_future_rt <- function(future = c("latest", "project", "estimate"),
                             delay = 0) {
  out <- list(fixed = FALSE, from = 0)
  if (is.character(future)) {
    future <- arg_match(future)
    if (future != "project") {
      out$fixed <- TRUE
      out$from <- ifelse(future == "latest", 0, -delay)
    }
  } else if (is.numeric(future)) {
    out$fixed <- TRUE
    out$from <- as.integer(future)
  }
  out
}

#' Create Time-varying Reproduction Number Data
#'
#' @description
#' Takes the output from [rt_opts()] and converts it into a list understood by
#' stan.
#'
#' @param rt A list of options as generated by [rt_opts()] defining Rt
#' estimation. Defaults to [rt_opts()]. To generate new infections using
#' the non-mechanistic model instead of the renewal equation model, use
#' `rt = NULL`. The non-mechanistic model internally uses the setting
#' `rt = rt_opts(use_rt = FALSE)`.
#'
#' @param breakpoints An integer vector (binary) indicating the location of
#' breakpoints.
#'
#' @param horizon Numeric, forecast horizon.
#'
#' @param data A `data.table` of case data (optional). Used for validation
#' checks.
#'
#' @importFrom cli cli_abort cli_warn
#'
#' @seealso [rt_opts()]
#' @return A list of settings defining the time-varying reproduction number
#' @inheritParams create_future_rt
#' @keywords internal
#' @examples
#' \dontrun{
#' # default Rt data
#' create_rt_data()
#'
#' # settings when no Rt is desired
#' create_rt_data(rt = NULL)
#'
#' # using breakpoints
#' create_rt_data(rt_opts(use_breakpoints = TRUE), breakpoints = rep(1, 10))
#'
#' # using random walk
#' create_rt_data(rt_opts(rw = 7), breakpoints = rep(1, 10))
#' }
create_rt_data <- function(rt = rt_opts(), breakpoints = NULL,
                           delay = 0, horizon = 0, data = NULL) {
  # Define if GP is on or off
  if (is.null(rt)) {
    rt <- rt_opts(use_rt = FALSE)
  }
  # define future Rt arguments
  future_rt <- create_future_rt(
    future = rt$future,
    delay = delay
  )
  # apply random walk
  if (rt$rw != 0) {
    if (is.null(breakpoints)) {
      cli_abort(
        c(
          "!" = "breakpoints must be supplied when using random walk."
        )
      )
    }

    breakpoints <- seq_along(breakpoints)
    breakpoints <- floor(breakpoints / rt$rw)
    if (rt$future != "project") {
      max_bps <- length(breakpoints) - horizon + future_rt$from
      if (max_bps < length(breakpoints)) {
        breakpoints[(max_bps + 1):length(breakpoints)] <- breakpoints[max_bps]
      }
    }
  } else {
    breakpoints <- cumsum(breakpoints)
  }

  if (sum(breakpoints) == 0) {
    rt$use_breakpoints <- FALSE
  }
  # add a shift for 0 effect in breakpoints
  breakpoints <- breakpoints + 1

  # Get pop_floor value
  pop_floor_value <- rt$pop_floor

  # Warn if fixed population is smaller than cumulative cases
  if (rt$pop != Fixed(0) && !is.null(data) &&
        get_distribution(rt$pop) == "fixed") {
    pop_value <- mean(rt$pop, ignore_uncertainty = TRUE)
    total_cases <- sum(data[!is.na(confirm)]$confirm, na.rm = TRUE)

    if (pop_value < total_cases) {
      # nolint start: duplicate_argument_linter
      cli_warn(
        c(
          "!" = "Population ({pop_value}) is smaller than cumulative cases",
          "!" = "({total_cases}).",
          "i" = "This suggests the population value is incorrect.",
          "i" = "Consider using the total at-risk population, not a subset."
        )
      )
      # nolint end
    }
  }

  # breakpoints (an out-of-step random walk on Rt) are superseded by the random
  # walk prior; with Rt expressed as a state they are no longer applied
  bp_n <- ifelse(rt$use_breakpoints, max(breakpoints) - 1, 0)
  if (bp_n > 0) {
    lifecycle::deprecate_warn(
      "1.10.0", "rt_opts(use_breakpoints)",
      details = paste(
        "Breakpoints are superseded by a random-walk Rt prior",
        "(`rt_opts(prior = RW(...))`) and are now ignored."
      )
    )
    bp_n <- 0
    breakpoints <- rep(1L, length(breakpoints))
  }

  # map settings to underlying gp stan requirements
  rt_data <- list(
    estimate_r = as.numeric(rt$use_rt),
    bp_n = bp_n,
    breakpoints = breakpoints,
    use_pop =
      as.integer(rt$pop != Fixed(0)) + as.integer(rt$pop_period == "all"),
    pop_floor = pop_floor_value,
    future_time = horizon - future_rt$from,
    growth_method = list(
      "infections" = 0, "infectiousness" = 1
    )[[rt$growth_method]]
  )
  rt_data
}
#' Create Back Calculation Data
#'
#' @description
#' Takes the output of [backcalc_opts()] and converts it into a list understood
#' by stan.
#'
#' @param backcalc A list of options as generated by [backcalc_opts()] to
#' define the back calculation. Defaults to [backcalc_opts()].
#'
#' @seealso [backcalc_opts()]
#' @importFrom data.table fcase
#' @return A list of settings defining the Gaussian process
#' @keywords internal
create_backcalc_data <- function(backcalc = backcalc_opts()) {
  list(
    rt_half_window = as.integer((backcalc$rt_window - 1) / 2)
  )
}

#' Create Observation Model Settings
#'
#' @description
#' Takes the output of [obs_opts()] and converts it into a list understood
#' by stan.
#' @param obs A list of options as generated by [obs_opts()] defining the
#' observation model. Defaults to [obs_opts()].
#' @param dates A vector of dates used to calculate the day of the week.
#' @seealso [obs_opts()]
#' @return A list of settings ready to be passed to stan defining
#' the Observation Model
#' @keywords internal
#' @examples
#' \dontrun{
#' dates <- seq(as.Date("2020-03-15"), by = "days", length.out = 15)
#' # default observation model data
#' create_obs_model(dates = dates)
#'
#' # Poisson observation model
#' create_obs_model(obs_opts(family = "poisson"), dates = dates)
#'
#' # Applying a observation scaling to the data
#' create_obs_model(
#'   obs_opts(scale = Normal(mean = 0.4, sd = 0.01)),
#'   dates = dates
#' )
#'
#' # Apply a custom week week length
#' create_obs_model(obs_opts(week_length = 3), dates = dates)
#' }
create_obs_model <- function(obs = obs_opts(), dates) {
  opts <- list(
    model_type = as.numeric(obs$family == "negbin"),
    week_effect = ifelse(obs$week_effect, obs$week_length, 1),
    obs_weight = obs$weight,
    obs_scale = as.integer(
      is_state_spec(obs$scale) || obs$scale != Fixed(1)
    ),
    likelihood = as.numeric(obs$likelihood),
    return_likelihood = as.numeric(obs$return_likelihood)
  )

  opts$day_of_week <- add_day_of_week(dates, opts$week_effect)

  opts
}

#' Create Stan Data Required for estimate_infections
#'
#' @description
#' Takes the output of [stan_opts()] and converts it into a list understood by
#' stan. Internally calls the other `create_` family of functions to
#' construct a single list for input into stan with all data required
#' present.
#'
#' @param seeding_time Integer; seeding time, usually obtained using
#' [get_seeding_time()].
#'
#' @inheritParams estimate_infections
#' @inheritParams create_obs_model
#' @inheritParams create_rt_data
#' @inheritParams create_backcalc_data
#' @inheritParams create_stan_params
#' @importFrom stats lm
#' @importFrom purrr safely
#' @return A list of stan data
#' @keywords internal
#' @examples
#' \dontrun{
#' create_stan_data(
#'   example_confirmed, 7, rt_opts(), gp_opts(), obs_opts(), 7,
#'   backcalc_opts(), params = list()
#' )
#' }
create_stan_data <- function(data, seeding_time, rt, obs, backcalc,
                             forecast, params) {
  cases <- data[(seeding_time + 1):.N]
  cases[, lookup := seq_len(.N)]
  case_times <- cases[!is.na(confirm), lookup]
  accumulate <- get_accumulate(cases)
  imputed_times <- cases[!accumulate, lookup]
  confirmed_cases <- cases[1:(.N - forecast$horizon)]$confirm

  stan_data <- list(
    cases = confirmed_cases[!is.na(confirmed_cases)],
    any_accumulate = as.integer(any(accumulate)),
    case_times = as.integer(case_times),
    imputed_times = as.integer(imputed_times),
    accumulate = as.integer(accumulate),
    lt = length(case_times),
    it = length(imputed_times),
    t = length(data$date),
    burn_in = 0,
    seeding_time = seeding_time,
    horizon = forecast$horizon
  )
  # add Rt data
  stan_data <- c(
    stan_data,
    create_rt_data(rt,
      breakpoints = cases$breakpoint,
      delay = stan_data$seeding_time, horizon = stan_data$horizon,
      data = data
    )
  )
  # backcalculation settings
  stan_data <- c(stan_data, create_backcalc_data(backcalc))

  # observation model data
  stan_data <- c(
    stan_data,
    create_obs_model(obs, dates = cases$date)
  )

  # parameters
  stan_data <- c(
    stan_data,
    # Rt (R, renewal model) and latent infections (I, back-calculation model)
    # are expressed as states; time-varying observation parameters follow later
    create_stan_params(
      params, states_supported = c("R", "I"), seeding_time = seeding_time
    )
  )

  stan_data
}

##' Create initial conditions for delays
##'
##' @inheritParams create_initial_conditions
##' @return A list of initial conditions for delays
##' @importFrom stats rgamma
##' @keywords internal
create_delay_inits <- function(stan_data) {
  out <- list()
  if (stan_data$delay_n_p > 0) {
    out$delay_params <- array(truncnorm::rtruncnorm(
      n = stan_data$delay_params_length, a = stan_data$delay_params_lower,
      mean = stan_data$delay_params_mean, sd = stan_data$delay_params_sd * 0.1
    ))
  } else {
    out$delay_params <- array(numeric(0))
  }
  ## seed the gamma-trick raw vector from its prior so chains start
  ## near the configured Dirichlet mean rather than from generic random
  ## values
  if (isTRUE(stan_data$delay_np_est_length > 0)) {
    out$delay_np_est_raw <- array(rgamma(
      n = stan_data$delay_np_est_length,
      shape = stan_data$delay_np_est_alpha,
      rate = 1
    ))
  } else {
    out$delay_np_est_raw <- array(numeric(0))
  }
  out
}

#' Create Initial Conditions Generating Function
#' @description
#' Uses the output of [create_stan_data()] to create a function which can be
#' used to sample from the prior distributions (or as close as possible) for
#' parameters. Used in order to initialise each stan chain within a range of
#' plausible values.
#' @param stan_data A list of data as produced by [create_stan_data()].
#' @inheritParams create_stan_params
#' @return An initial condition generating function
#' @importFrom purrr map2_dbl transpose
#' @importFrom truncnorm rtruncnorm
#' @importFrom data.table fcase
#' @keywords internal
create_initial_conditions <- function(stan_data, params) {
  function() {
    out <- create_delay_inits(stan_data)

    ## unwrap time-varying states to their level prior for initialisation
    state_flags <- vapply(transpose(params)$dist, is_state_spec, logical(1))
    if (any(state_flags)) {
      for (i in which(state_flags)) {
        params[[i]]$dist <- params[[i]]$dist$prior
      }
    }

    if (stan_data$estimate_r == 1) {
      out$initial_infections <- array(rnorm(1))
    } else {
      out$initial_infections <- array(numeric(0))
    }

    if (stan_data$bp_n > 0) {
      out$bp_sd <- array(truncnorm::rtruncnorm(1, a = 0, mean = 0, sd = 0.1))
      out$bp_effects <- array(rnorm(stan_data$bp_n, 0, 0.1))
    } else {
      out$bp_sd <- array(numeric(0))
      out$bp_effects <- array(numeric(0))
    }
    if (stan_data$week_effect > 0) {
      out$day_of_week_simplex <- array(
        rep(1 / stan_data$week_effect, stan_data$week_effect)
      )
    }
    tparams <- transpose(params)
    null <- vapply(tparams$dist, is.null, logical(1))
    fixed <- vapply(
      tparams$dist[!null], get_distribution, character(1)
    ) == "fixed"
    param_means <- vapply(
      tparams$dist[!null][!fixed],
      mean,
      ignore_uncertainty = FALSE,
      FUN.VALUE = numeric(1)
    )
    param_sds <- vapply(
      tparams$dist[!null][!fixed],
      sd,
      ignore_uncertainty = FALSE,
      FUN.VALUE = numeric(1)
    )
    out$params <- array(truncnorm::rtruncnorm(
      stan_data$n_params_variable,
      a = stan_data$params_lower,
      b = stan_data$params_upper,
      mean = param_means, sd = param_sds
    ))

    ## time-varying states vary over a free-noise window, mirroring the
    ## computation in the Stan model (transformed data). The observation window
    ## runs to the end of the data; the `future` setting (state_future_fixed /
    ## state_future_from) sets how far the state varies into the horizon.
    ## truncnorm::rtruncnorm() returns NULL for n = 0, so guard zero counts
    rtruncnorm0 <- function(n, ...) {
      if (n > 0) truncnorm::rtruncnorm(n, ...) else numeric(0)
    }
    data_window <- if (stan_data$estimate_r == 1) {
      stan_data$t - stan_data$seeding_time - stan_data$horizon
    } else {
      stan_data$t - stan_data$horizon
    }
    full_window <- if (stan_data$estimate_r == 1) {
      stan_data$t - stan_data$seeding_time
    } else {
      stan_data$t
    }
    state_future_from <- stan_data$state_future_from %||% 0L
    state_obs <- if ((stan_data$state_future_fixed %||% 1L) == 0) {
      full_window
    } else {
      min(full_window, max(1, data_window + state_future_from))
    }
    rw_period <- stan_data$state_rw_period %||% 1L
    state_rw_n <- max(0, ceiling(state_obs / rw_period) - 1)
    out$state_rw_sd <- array(
      rtruncnorm0(stan_data$n_rw_states, a = 0, mean = 0, sd = 0.1)
    )
    out$state_rw_steps <- array(
      rnorm(stan_data$n_rw_states * state_rw_n, 0, 0.1)
    )
    gp_m <- if (stan_data$n_gp_states > 0) {
      ceiling(state_obs * stan_data$gp_basis_prop)
    } else {
      0
    }
    out$state_gp_eta <- array(rnorm(stan_data$n_gp_states * gp_m, 0, 0.1))
    out$state_gp_alpha <- array(
      rtruncnorm0(stan_data$n_gp_states, a = 0, mean = 0, sd = 0.1)
    )
    out$state_gp_rho <- array(
      rtruncnorm0(
        stan_data$n_gp_states, a = 0, mean = state_obs / 2, sd = state_obs / 4
      )
    )
    out
  }
}

#' Create a List of Stan Arguments
#'
#' @description
#' Generates a list of arguments as required by the stan sampling functions by
#' combining the required options with data, and type of initialisation.
#' Initialisation defaults to random but it is expected that
#' [create_initial_conditions()] will be used.
#'
#' @param stan A list of stan options as generated by [stan_opts()]. Defaults
#' to [stan_opts()]. Can be used to override `data`, `init`, and `verbose`
#' settings if desired.
#'
#' @param data A list of stan data as created by [create_stan_data()]
#'
#' @param init Initial conditions passed to `{rstan}`. Defaults to "random"
#' (initial values randomly drawn between -2 and 2) but can also be a
#' function (as supplied by [create_initial_conditions()]).
#'
#' @param model Character, name of the model for which arguments are
#' to be created.
#' @param fixed_param Logical, defaults to `FALSE`. Should arguments be
#' created to sample from fixed parameters (used by simulation functions).
#'
#' @param verbose Logical, defaults to `FALSE`. Should verbose progress
#' messages be returned.
#'
#' @importFrom utils modifyList
#'
#' @return A list of stan arguments
#' @keywords internal
#' @examples
#' \dontrun{
#' # default settings
#' create_stan_args()
#'
#' # increasing warmup
#' create_stan_args(stan = stan_opts(warmup = 1000))
#' }
create_stan_args <- function(stan = stan_opts(),
                             data = NULL,
                             init = "random",
                             model = "estimate_infections",
                             fixed_param = FALSE,
                             verbose = FALSE) {
  if (fixed_param) {
    if (stan$backend == "rstan") {
      stan$algorithm <- "Fixed_param"
    } else if (stan$backend == "cmdstanr") {
      stan$fixed_param <- TRUE
      stan$adapt_delta <- NULL
      stan$max_treedepth <- NULL
    }
  }
  ## generate stan model
  if (is.null(stan$object)) {
    stan$object <- epinow2_stan_model(stan$backend, model)
    stan$backend <- NULL
  }
  # cmdstanr doesn't have an init = "random" argument
  if (is.character(init) && init == "random" &&
        inherits(stan$object, "CmdStanModel")) {
    init <- 2
  }
  # set up shared default arguments
  stan_args <- list(
    data = data,
    init = init,
    refresh = ifelse(verbose, 50, 0)
  )
  stan_args <- modifyList(stan_args, stan)
  stan_args$return_fit <- NULL
  stan_args
}

##' Build Stan data for estimated nonparametric delays
##'
##' Takes the nonparametric delays and the PMF group boundaries and
##' returns the ragged-array fields that Stan needs to map a
##' normalised Dirichlet draw back into `delay_np_pmf`.
##'
##' Structural zeros (entries where the prior alpha is zero, e.g. the
##' `t = 0` generation-time bin) are dropped from the estimated
##' parameter vector so Stan never sees a `Gamma(0, 1)` rate. Their
##' positions are still held by the fixed `delay_np_pmf` entries and
##' are left untouched at sampling time.
##'
##' @param np_delays A list of nonparametric `dist_spec` objects in
##'   their original order. Each estimated entry must carry an
##'   `$alpha` numeric vector aligned with its PMF.
##' @param np_pmf_groups Integer vector of 1-indexed PMF group
##'   boundaries (output of `create_stan_delays()`).
##' @return A named list with `n_np_est`, `np_est_which`,
##'   `np_est_alpha`, `np_est_pos`, `np_est_groups`, and
##'   `np_est_length`. Empty arrays are returned when no delays are
##'   estimated.
##' @keywords internal
build_np_est_data <- function(np_delays, np_pmf_groups) {
  np_estimated <- vapply(
    np_delays, function(x) isTRUE(x$estimated), logical(1)
  )
  est_np_indices <- which(np_estimated)
  est_np_delays <- np_delays[np_estimated]
  n_np_est <- sum(np_estimated)

  if (n_np_est == 0L) {
    return(list(
      n_np_est = 0L,
      np_est_which = array(integer(0)),
      np_est_alpha = array(numeric(0)),
      np_est_pos = array(integer(0)),
      np_est_groups = array(1L),
      np_est_length = 0L
    ))
  }

  all_alphas <- list()
  all_pos <- list()
  for (k in seq_along(est_np_delays)) {
    alpha_k <- est_np_delays[[k]]$alpha
    np_id <- est_np_indices[k]
    pmf_start <- np_pmf_groups[np_id]
    positive <- which(alpha_k > 0)
    all_alphas[[k]] <- alpha_k[positive]
    all_pos[[k]] <- pmf_start + positive - 1L
  }
  est_np_alphas <- unname(as.numeric(unlist(all_alphas)))
  est_np_positions <- as.integer(unlist(all_pos))
  est_np_lengths <- lengths(all_alphas)

  list(
    n_np_est = n_np_est,
    np_est_which = array(est_np_indices),
    np_est_alpha = array(est_np_alphas),
    np_est_pos = array(est_np_positions),
    np_est_groups = array(c(0, cumsum(est_np_lengths)) + 1),
    np_est_length = sum(est_np_lengths)
  )
}

##' Create delay variables for stan
##'
##' @param ... Named delay distributions. The names are assigned to IDs
##' @param time_points Integer, the number of time points in the data;
##'   determines weight associated with weighted delay priors; default: 1
##' @return A list of variables as expected by the stan model
##' @importFrom purrr transpose map flatten
##' @keywords internal
create_stan_delays <- function(..., time_points = 1L) {
  delays <- list(...)
  delay_names <- names(delays)

  ## discretise
  delays <- map(delays, discretise, strict = FALSE)
  delays <- map(delays, collapse)
  ## get maximum delays
  bounded_delays <- map(delays, function(x) discretise(fix_parameters(x)))
  max_delay <- unname(as.numeric(flatten(map(bounded_delays, max))))
  ## number of different non-empty types
  type_n <- vapply(delays, ndist, integer(1))

  ## Create delay_id_* variables pointing to delay_types_groups index
  ## Similar to param_id_* in create_stan_params()
  delay_ids <- rep(0L, length(type_n))
  delay_ids[type_n > 0] <- seq_len(sum(type_n > 0))
  names(delay_ids) <- paste("delay_id", delay_names, sep = "_")

  ## create "flat version" of delays, i.e. a list of all the delays (including
  ## elements of composite delays)
  if (length(delays) > 1) {
    flat_delays <- do.call(c, delays)
  } else {
    flat_delays <- delays
  }
  parametric <- unname(
    vapply(flat_delays, get_distribution, character(1)) != "nonparametric"
  )
  param_length <- unname(vapply(flat_delays[parametric], function(x) {
    length(get_parameters(x))
  }, numeric(1)))
  nonparam_length <- unname(vapply(flat_delays[!parametric], function(x) {
    length(x$pmf)
  }, numeric(1)))
  distributions <- unname(as.character(
    map(flat_delays[parametric], get_distribution)
  ))

  ## create stan object
  ret <- list(
    n = length(flat_delays),
    n_p = sum(parametric),
    n_np = sum(!parametric),
    types = sum(type_n > 0),
    types_p = array(as.integer(parametric))
  )

  ## delay identifiers
  ret$types_id <- integer(0)
  ret$types_id[ret$types_p == 1] <- seq_len(ret$n_p)
  ret$types_id[ret$types_p == 0] <- seq_len(ret$n_np)
  ret$types_id <- array(ret$types_id)
  ## map delays to identifiers
  ret$types_groups <- array(c(0, cumsum(unname(type_n[type_n > 0]))) + 1)

  ret$params_mean <- array(unname(as.numeric(
    map(flatten(map(flat_delays[parametric], get_parameters)), mean)
  )))
  ret$params_sd <- array(unname(as.numeric(
    map(flatten(map(flat_delays[parametric], get_parameters)), sd)
  )))
  ret$params_sd[is.na(ret$params_sd)] <- 0
  ret$max <- array(max_delay[parametric])

  ret$np_pmf <- array(unname(as.numeric(
    flatten(map(flat_delays[!parametric], get_pmf))
  )))
  ## get non zero length delay pmf lengths
  ret$np_pmf_groups <- array(c(0, cumsum(nonparam_length)) + 1)
  ## calculate total np pmf length
  ret$np_pmf_length <- sum(nonparam_length)

  ## estimated nonparametric delays
  ret <- c(
    ret,
    build_np_est_data(flat_delays[!parametric], ret$np_pmf_groups)
  )

  ## get non zero length param lengths
  ret$params_groups <- array(c(0, cumsum(param_length)) + 1)
  ## calculate total param length
  ret$params_length <- sum(param_length)
  ## set lower bounds
  ret$params_lower <- array(unname(as.numeric(flatten(
    map(flat_delays[parametric], function(x) {
      lower_bounds(get_distribution(x))[names(get_parameters(x))]
    })
  ))))
  ## assign prior weights
  weight_priors <- vapply(
    delays[parametric], attr, "weight_prior",
    FUN.VALUE = logical(1)
  )
  ret$weight <- array(rep(1, ret$n_p))
  ret$weight[weight_priors] <- time_points
  ## assign distribution
  ret$dist <- array(vapply(
    distributions, primarycensored::pcd_stan_dist_id, integer(1)
  ))

  names(ret) <- paste("delay", names(ret), sep = "_")
  ret <- c(ret, as.list(delay_ids))

  ret
}

##' Create parameters for stan
##'
##' @param params A list of `<EpiNow2.params>` as created by [make_param()]
##'
##' @param states_supported Character vector of parameter names for which the
##'   calling model can consume time-varying states (created by [GP()] /
##'   [RW()]). Defaults to none, so any state specification raises an error.
##'   A model passes the names whose state data its stan code handles.
##'
##' @return A list of variables as expected by the stan model
##' @importFrom data.table fcase
##' @importFrom purrr transpose
##' @keywords internal
create_stan_params <- function(params, states_supported = character(0),
                               seeding_time = 0L) {
  tparams <- transpose(params)
  ## set IDs of any parameters that is NULL to 0 and remove
  null_params <- vapply(tparams$dist, is.null, logical(1))
  null_ids <- rep(0, sum(null_params))
  if (length(null_ids) > 0) {
    names(null_ids) <- paste(
      "param_id", tparams$name[null_params], sep = "_"
    )
    params <- params[!null_params]
    tparams <- transpose(params)
  }

  ## extract any time-varying (state) specifications. The parameter's level
  ## prior flows through the normal parameter machinery; the state is layered
  ## on top in the model via the data from create_state_data().
  state_flags <- vapply(tparams$dist, is_state_spec, logical(1))
  state_data <- create_state_data(
    params, state_flags, states_supported, seeding_time = seeding_time
  )
  if (any(state_flags)) {
    for (i in which(state_flags)) {
      params[[i]]$dist <- params[[i]]$dist$prior
    }
    tparams <- transpose(params)
  }

  ## initialise variables
  params_fixed_lookup <- rep(0L, length(params))
  params_variable_lookup <- rep(0L, length(params))

  ## identify fixed/variable parameters
  fixed <- vapply(tparams$dist, get_distribution, character(1)) == "fixed"
  params_fixed_lookup[fixed] <- seq_along(which(fixed))
  params_variable_lookup[!fixed] <- seq_along(which(!fixed))

  ## lower bounds
  lower_bounds <- unlist(tparams$lower_bound[!fixed])
  if (is.null(lower_bounds)) {
    params_lower <- array(numeric(0))
  } else {
    params_lower <- lower_bounds
  }

  ## upper bounds
  params_upper <- vapply(tparams$dist[!fixed], max, numeric(1))

  ## prior distributions
  prior_dist_name <- vapply(
    tparams$dist[!fixed], get_distribution, character(1)
  )
  prior_dist <- fcase(
    prior_dist_name == "lognormal", 0L,
    prior_dist_name == "gamma", 1L,
    prior_dist_name == "normal", 2L
  )
  ## parameters
  prior_dist_params <- lapply(tparams$dist[!fixed], get_parameters)
  prior_dist_params_lengths <- lengths(prior_dist_params)

  ## check none of the parameters are uncertain
  prior_uncertain <- vapply(prior_dist_params, function(x) {
    !all(vapply(x, is.numeric, logical(1)))
  }, logical(1))
  if (any(prior_uncertain)) {
    uncertain_priors <- tparams$name[!fixed][prior_uncertain] # nolint: object_usage_linter
    cli_abort(
      c(
        "!" = "Parameter prior distribution{?s} for {.var {uncertain_priors}}
        cannot have uncertain parameters."
      )
    )
  }

  prior_dist_params <- unlist(prior_dist_params)
  if (is.null(prior_dist_params)) {
    prior_dist_params <- numeric(0)
  }

  ## for init-anchored states the level is free scaffolding: its prior is
  ## applied to the derived initial value instead, so skip it in the prior path
  params_prior_skip <- rep(0L, length(params) - sum(fixed))
  init_state_ids <- state_data$state_param_id[state_data$state_anchor == 1]
  for (pid in init_state_ids) {
    vpos <- params_variable_lookup[pid]
    if (vpos > 0) {
      params_prior_skip[vpos] <- 1L
    }
  }

  ## extract distributions and parameters
  ret <- list(
    n_params_variable = length(params) - sum(fixed),
    n_params_fixed = sum(fixed),
    params_lower = array(params_lower),
    params_upper = array(params_upper),
    params_prior_skip = array(params_prior_skip),
    params_fixed_lookup = array(params_fixed_lookup),
    params_variable_lookup = array(params_variable_lookup),
    params_value = array(vapply(
      tparams$dist[fixed], function(x) get_parameters(x)$value, numeric(1)
    )),
    prior_dist = array(prior_dist),
    prior_dist_params_length = sum(prior_dist_params_lengths),
    prior_dist_params = array(prior_dist_params)
  )
  ids <- seq_along(params)
  if (length(ids) > 0) {
    names(ids) <- paste("param_id", tparams$name, sep = "_")
  }
  c(ret, state_data, as.list(ids), as.list(null_ids))
}

##' Create time-varying state data for stan
##'
##' Builds the minimal configuration the stan model needs to layer a stochastic
##' state on top of a parameter's level (see [create_stan_params()]). The
##' trajectory length and centring window are derived in stan from the modelled
##' time, so only the state type, link, target parameter and step standard
##' deviation prior are emitted here.
##'
##' @param params A list of `<EpiNow2.params>` after `NULL` parameters have been
##'   removed, so that positions match the stan parameter ids.
##' @param state_flags Logical vector flagging which entries of `params` carry
##'   a state specification.
##' @param states_supported Character vector of parameter names the calling
##'   model can consume a time-varying state for. A state on any other parameter
##'   errors.
##' @return A named list of stan data items describing the states.
##' @importFrom data.table fcase
##' @keywords internal
create_state_data <- function(params, state_flags,
                              states_supported = character(0),
                              seeding_time = 0L) {
  empty <- list(
    n_states = 0L,
    state_param_id = array(integer(0)),
    state_type = array(integer(0)),
    state_link = array(integer(0)),
    state_pos = array(integer(0)),
    state_anchor = array(integer(0)),
    state_init_dist = array(integer(0)),
    state_init_dist_params = array(numeric(0)),
    state_init_lower = array(numeric(0)),
    state_init_upper = array(numeric(0)),
    state_future_fixed = 1L,
    state_future_from = 0L,
    n_rw_states = 0L,
    rw_sd_dist = array(integer(0)),
    rw_sd_dist_params = array(numeric(0)),
    state_rw_period = 1L,
    n_gp_states = 0L,
    gp_basis_prop = 0.2,
    gp_boundary_scale = 1.5,
    gp_kernel = array(integer(0)),
    gp_nu = array(numeric(0)),
    gp_alpha_dist = array(integer(0)),
    gp_alpha_dist_params = array(numeric(0)),
    gp_rho_dist = array(integer(0)),
    gp_rho_dist_params = array(numeric(0))
  )
  if (!any(state_flags)) {
    return(empty)
  }

  ## integer code for a simple (lognormal/gamma/normal) prior distribution
  dist_code <- function(d) {
    fcase(
      get_distribution(d) == "lognormal", 0L,
      get_distribution(d) == "gamma", 1L,
      get_distribution(d) == "normal", 2L
    )
  }
  ## the two prior parameters, requiring them to be certain (numeric)
  numeric_params <- function(d, what, name) {
    pars <- get_parameters(d)
    if (!all(vapply(pars, is.numeric, logical(1)))) {
      cli_abort(c(
        "!" = "The {what} prior for time-varying parameter {.var {name}} cannot
        have uncertain parameters."
      ))
    }
    as.numeric(unlist(pars))
  }
  ## resolve a state's `future` setting into the (fixed, from) pair the model
  ## uses to size the free-noise window over the forecast horizon. "estimate"
  ## fixes the state a seeding time before the end of the data, where the most
  ## recent estimates are least informed.
  resolve_future <- function(future) {
    if (is.numeric(future)) {
      return(list(fixed = 1L, from = as.integer(future)))
    }
    switch(future,
      latest = list(fixed = 1L, from = 0L),
      project = list(fixed = 0L, from = 0L),
      estimate = list(fixed = 1L, from = -as.integer(seeding_time))
    )
  }

  idx <- which(state_flags)
  n <- length(idx)
  param_id <- integer(n)
  type <- integer(n)
  link <- integer(n)
  pos <- integer(n)
  anchor <- integer(n)
  init_dist <- integer(n)
  init_params <- numeric(2 * n)
  init_lower <- numeric(n)
  init_upper <- numeric(n)
  future_fixed <- integer(n)
  future_from <- integer(n)
  rw_sd_dist <- integer(0)
  rw_sd_params <- numeric(0)
  rw_period <- integer(0)
  gp_kernel <- integer(0)
  gp_nu <- numeric(0)
  gp_alpha_dist <- integer(0)
  gp_alpha_params <- numeric(0)
  gp_rho_dist <- integer(0)
  gp_rho_params <- numeric(0)
  gp_basis_prop <- empty$gp_basis_prop
  gp_boundary_scale <- empty$gp_boundary_scale
  n_rw <- 0L
  n_gp <- 0L

  for (j in seq_len(n)) {
    spec <- params[[idx[j]]]$dist
    name <- params[[idx[j]]]$name # nolint: object_usage_linter
    if (!name %in% states_supported) {
      if (length(states_supported) == 0) {
        cli_abort(c(
          "!" = "Time-varying parameter {.var {name}} ({.cls state_spec}) is not
          supported by this model."
        ))
      }
      cli_abort(c(
        "!" = "Time-varying {.var {name}} is not yet supported.",
        "i" = "Currently supported: {.var {states_supported}}."
      ))
    }
    if (!is(spec$prior, "dist_spec")) {
      cli_abort(c(
        "!" = "Known (numeric) trajectories are not yet supported for
        time-varying parameter {.var {name}}."
      ))
    }
    param_id[j] <- idx[j]
    link[j] <- 0L # log
    resolved_future <- resolve_future(spec$future %||% "latest")
    future_fixed[j] <- resolved_future$fixed
    future_from[j] <- resolved_future$from
    if (spec$anchor == "init") {
      ## centred non-stationary state: the level is free scaffolding and the
      ## user prior is applied to the derived initial value (with a Jacobian)
      anchor[j] <- 1L
      packed <- pack_init_prior(
        spec$prior, lower_bound = params[[idx[j]]]$lower_bound %||% 0
      )
      init_dist[j] <- packed$dist_type
      init_params[(2 * j - 1):(2 * j)] <- packed$params
      init_lower[j] <- packed$lower
      init_upper[j] <- packed$upper
    }
    if (spec$type == "rw") {
      type[j] <- 0L
      n_rw <- n_rw + 1L
      pos[j] <- n_rw
      step_sd <- spec$settings$sd
      rw_sd_dist <- c(rw_sd_dist, dist_code(step_sd))
      rw_sd_params <- c(rw_sd_params, numeric_params(step_sd, "step sd", name))
      rw_period <- c(rw_period, spec$settings$period %||% 1L)
    } else {
      gp <- spec$settings
      if (gp$kernel == "periodic") {
        cli_abort(c(
          "!" = "Periodic kernels are not supported for time-varying parameter
          {.var {name}}."
        ))
      }
      type[j] <- 1L
      n_gp <- n_gp + 1L
      pos[j] <- n_gp
      gp_kernel <- c(gp_kernel, fcase(
        gp$kernel == "se", 0L,
        default = 2L # matern or ou
      ))
      gp_nu <- c(gp_nu, gp$matern_order)
      gp_alpha_dist <- c(gp_alpha_dist, dist_code(gp$alpha))
      gp_alpha_params <- c(
        gp_alpha_params, numeric_params(gp$alpha, "alpha", name)
      )
      gp_rho_dist <- c(gp_rho_dist, dist_code(gp$ls))
      gp_rho_params <- c(
        gp_rho_params, numeric_params(gp$ls, "lengthscale", name)
      )
      gp_basis_prop <- gp$basis_prop
      gp_boundary_scale <- gp$boundary_scale
    }
  }

  # a single random walk period is shared across random walk states
  rw_period <- unique(rw_period)
  if (length(rw_period) > 1) {
    cli_abort(c(
      "!" = "Different random walk periods across states are not yet supported."
    ))
  }
  state_rw_period <- if (length(rw_period) == 1) rw_period else 1L

  # a single forecast-horizon (`future`) behaviour is shared across states
  future_pairs <- unique(data.frame(fixed = future_fixed, from = future_from))
  if (nrow(future_pairs) > 1) {
    cli_abort(c(
      "!" = "Different {.arg future} settings across time-varying states are not
      yet supported.",
      "i" = "Use the same {.arg future} for every state in the model."
    ))
  }

  list(
    n_states = n,
    state_param_id = array(as.integer(param_id)),
    state_type = array(type),
    state_link = array(link),
    state_pos = array(as.integer(pos)),
    state_anchor = array(anchor),
    state_init_dist = array(init_dist),
    state_init_dist_params = array(init_params),
    state_init_lower = array(init_lower),
    state_init_upper = array(init_upper),
    state_future_fixed = future_pairs$fixed,
    state_future_from = future_pairs$from,
    n_rw_states = n_rw,
    rw_sd_dist = array(rw_sd_dist),
    rw_sd_dist_params = array(rw_sd_params),
    state_rw_period = state_rw_period,
    n_gp_states = n_gp,
    gp_basis_prop = gp_basis_prop,
    gp_boundary_scale = gp_boundary_scale,
    gp_kernel = array(gp_kernel),
    gp_nu = array(gp_nu),
    gp_alpha_dist = array(gp_alpha_dist),
    gp_alpha_dist_params = array(gp_alpha_params),
    gp_rho_dist = array(gp_rho_dist),
    gp_rho_dist_params = array(gp_rho_params)
  )
}

#' Create summary output from infection estimation objects
#'
#'
#' This function creates summary output from infection estimation objects
#' (either `estimate_infections` or `forecast_infections`). It is used
#' internally by [summary.estimate_infections()] and
#' [summary.forecast_infections()] to provide a consistent summary interface.
#'
#' @param object An infection estimation object (either from
#'   [estimate_infections()] or [forecast_infections()]).
#'
#' @param type A character vector of data types to return. Defaults to
#'   "snapshot" but also supports "parameters". "snapshot" returns
#'   a summary at a given date (by default the latest date informed by data).
#'   "parameters" returns summarised parameter estimates that can be further
#'   filtered using `params` to show just the parameters of interest and date.
#'
#' @inheritParams summary.estimate_infections
#'
#' @param CrIs Numeric vector of credible intervals to calculate. Defaults
#'   to c(0.2, 0.5, 0.9).
#'
#' @param ... Additional arguments passed to [report_summary()].
#'
#' @return A `<data.frame>` of summary output, either a snapshot summary
#'   (via [report_summary()]) or parameter summaries (via
#'   [calc_summary_measures()]).
#'
#' @importFrom rlang arg_match
#' @seealso [summary.estimate_infections()] [summary.forecast_infections()]
#'   [report_summary()] [calc_summary_measures()]
#' @keywords internal
create_infection_summary <- function(object,
                                     type = c("snapshot", "parameters"),
                                     target_date = NULL, params = NULL,
                                     CrIs = c(0.2, 0.5, 0.9), ...) {
  type <- arg_match(type)

  samples <- get_samples(object)

  summarised <- calc_summary_measures(
    samples,
    summarise_by = c("date", "variable", "strat", "type"),
    order_by = c("variable", "date"),
    CrIs = CrIs
  )

  if (type == "snapshot") {
    if (is.null(target_date)) {
      target_date <- max(object$observations$date)
    } else {
      target_date <- as.Date(target_date)
    }
    out <- report_summary(
      summarised_estimates = summarised[date == target_date],
      rt_samples = samples[variable == "R"][
        date == target_date, .(sample, value)
      ],
      ...
    )
  } else if (type == "parameters") {
    out <- summarised
    if (!is.null(target_date)) {
      out <- out[date == as.Date(target_date)]
    }
    if (!is.null(params)) {
      out <- out[variable %in% params]
    }
  }
  out[]
}
