# Generated by rstantools.  Do not edit by hand.

# names of stan models
stanmodels <- c("estimate_infections", "estimate_secondary", "estimate_truncation", "exp", "gamma", "lnorm", "simulate_infections", "simulate_secondary", "tune_inv_gamma")

# load each stan module
Rcpp::loadModule("stan_fit4estimate_infections_mod", what = TRUE)
Rcpp::loadModule("stan_fit4estimate_secondary_mod", what = TRUE)
Rcpp::loadModule("stan_fit4estimate_truncation_mod", what = TRUE)
Rcpp::loadModule("stan_fit4exp_mod", what = TRUE)
Rcpp::loadModule("stan_fit4gamma_mod", what = TRUE)
Rcpp::loadModule("stan_fit4lnorm_mod", what = TRUE)
Rcpp::loadModule("stan_fit4simulate_infections_mod", what = TRUE)
Rcpp::loadModule("stan_fit4simulate_secondary_mod", what = TRUE)
Rcpp::loadModule("stan_fit4tune_inv_gamma_mod", what = TRUE)

# instantiate each stanmodel object
stanmodels <- sapply(stanmodels, function(model_name) {
  # create C++ code for stan model
  stan_file <- if(dir.exists("stan")) "stan" else file.path("inst", "stan")
  stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
  stanfit <- rstan::stanc_builder(stan_file,
                                  allow_undefined = TRUE,
                                  obfuscate_model_name = FALSE)
  stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
                            model_cppcode = stanfit$cppcode)
  # create stanmodel object
  methods::new(Class = "stanmodel",
               model_name = stanfit$model_name,
               model_code = stanfit$model_code,
               model_cpp = stanfit$model_cpp,
               mk_cppmodule = function(x) get(paste0("model_", model_name)))
})
