
# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
      - master
      - develop
  schedule:
    - cron: '5 4 * * 1'
  pull_request:
    branches:
      - main
      - master
      - develop
  workflow_dispatch:

name: R-CMD-check

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  R-CMD-check:
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release', rtools: ''}
          ## to reactivate once rstan is updated on CRAN
          ## - {os: windows-latest, r: 'release', rtools: '42'}
          - {os: ubuntu-latest,   r: 'release', rtools: ''}
          - {os: ubuntu-latest,   r: 'oldrel-1', rtools: ''}
          - {os: ubuntu-latest,   r: 'devel', rtools: ''}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      NOT_CRAN: true
      
    steps:
      - uses: actions/checkout@v3
        
      - name: Install cmdstan Linux system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev || true
          sudo apt-get install -y openmpi-bin openmpi-common libopenmpi-dev || true
          sudo apt-get install -y libpng-dev || true
          ## to remove once rstan is updated on CRAN
          sudo apt-get install -y libharfbuzz-dev libfribidi-dev || true
      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
          rtools-version: ${{ matrix.config.rtools }}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      ## to remove once rstan is updated on CRAN
      - name: Manually install dev versions of StanHeaders and rstan
        run: |
          install.packages("devtools")
          devtools::install_github("stan-dev/rstan/StanHeaders@develop")
          devtools::install_github("stan-dev/rstan/rstan/rstan@develop")
        shell: Rscript {0}

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
